"""add remetente to WhatsAppMensagem

Revision ID: 0e8796ecb99d
Revises: 8ef04da4e724
Create Date: 2025-10-02 19:28:37.455062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8796ecb99d'
down_revision = '8ef04da4e724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whats_app_mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('remetente', sa.String(length=50), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('recebido_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whats_app_mensagem')
    # ### end Alembic commands ###
