"""add_api_instance_to_usuario_crm

Revision ID: 334998351db0
Revises: f8a549bc73a8
Create Date: 2026-01-11 22:41:11.718864

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '334998351db0'
down_revision = 'f8a549bc73a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_crm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_instance', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_crm', schema=None) as batch_op:
        batch_op.drop_column('api_instance')
    # ### end Alembic commands ###
