"""add_authentication_and_permissions_to_usuario_crm

Revision ID: 3e2d88648226
Revises: add_usuario_crm_multitenancy
Create Date: 2026-01-10 19:38:41.853819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e2d88648226'
down_revision = 'add_usuario_crm_multitenancy'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removido drop de tabelas antigas para evitar erros
    # op.drop_table('pessoa_juridica')
    # op.drop_table('contato_empresa')
    # op.drop_table('whats_app_mensagem')
    # op.drop_table('pessoa_fisica')
    
    with op.batch_alter_table('usuario_crm', schema=None) as batch_op:
        # Adicionar novos campos de autenticação
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tipo_usuario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('usuario_pai_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('permissoes', sa.JSON(), nullable=True))
        batch_op.alter_column('numero_whatsapp',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        # Tentar remover constraint antiga se existir
        try:
            batch_op.drop_constraint('usuario_crm_numero_whatsapp_key', type_='unique')
        except:
            pass
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'usuario_crm', ['usuario_pai_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_mensagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prioridade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('whatsapp_mensagem_cliente_id_fkey'), 'cliente', ['cliente_id'], ['id'])
        batch_op.alter_column('recebido_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('numero',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('usuario_crm', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('usuario_crm_numero_whatsapp_key'), ['numero_whatsapp'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('numero_whatsapp',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('permissoes')
        batch_op.drop_column('usuario_pai_id')
        batch_op.drop_column('tipo_usuario')
        batch_op.drop_column('senha_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('mesa_negocio', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('tipo_pessoa',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.create_table('pessoa_fisica',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estado_civil', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('telefone_secundario', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('melhor_horario_contato', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferencia_canal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cep_pessoal', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rua_pessoal', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('numero_pessoal', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('bairro_pessoal', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cidade_pessoal', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado_pessoal', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('profissao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('empresa_trabalho', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('faixa_renda', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('interesses_principais', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('principais_dores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('produtos_interesse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('orcamentos_solicitados', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('compras_realizadas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_medio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('forma_pagamento_preferida', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recorrencia_compra', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('pessoa_fisica_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pessoa_fisica_pkey')),
    sa.UniqueConstraint('cliente_id', name=op.f('pessoa_fisica_cliente_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('whats_app_mensagem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('remetente', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recebido_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whats_app_mensagem_pkey'))
    )
    op.create_table('contato_empresa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pessoa_juridica_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('é_decisor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nivel_influencia', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pessoa_juridica_id'], ['pessoa_juridica.id'], name=op.f('contato_empresa_pessoa_juridica_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contato_empresa_pkey'))
    )
    op.create_table('pessoa_juridica',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('inscricao_estadual', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('data_abertura', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cnae', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ramo_atividade', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('porte_empresa', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('cep_comercial', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rua_comercial', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('numero_comercial', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('bairro_comercial', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cidade_comercial', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado_comercial', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('num_funcionarios_estimado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faturamento_estimado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('principais_produtos_servicos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('principais_desafios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objetivos_empresa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo_contrato', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valor_contrato', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('data_inicio_contrato', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_renovacao_contrato', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sla_acordado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('produtos_contratados', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('propostas_enviadas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_proposta', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('motivo_perda', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('historico_renegociacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('pessoa_juridica_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pessoa_juridica_pkey')),
    sa.UniqueConstraint('cliente_id', name=op.f('pessoa_juridica_cliente_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
