"""Criando tabelas iniciais

Revision ID: 8ef04da4e724
Revises: 
Create Date: 2025-09-30 21:10:09.860565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ef04da4e724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('recebido_em', sa.DateTime(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('whats_app_mensagem')
    with op.batch_alter_table('chatbot_regra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prioridade', sa.String(length=20), nullable=True))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('renda',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('faturamento',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('mesa_negocio', schema=None) as batch_op:
        batch_op.alter_column('topico',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('produtos',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               nullable=True)
        batch_op.alter_column('valor_total',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('situacao',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa_negocio', schema=None) as batch_op:
        batch_op.alter_column('situacao',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('valor_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('produtos',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('topico',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('faturamento',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('renda',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('chatbot_regra', schema=None) as batch_op:
        batch_op.drop_column('prioridade')

    op.create_table('whats_app_mensagem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('remetente', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_envio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_envio', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whats_app_mensagem_pkey'))
    )
    op.drop_table('whatsapp_mensagem')
    # ### end Alembic commands ###
