"""add observacoes to cliente

Revision ID: add_observacoes_cliente
Revises: add_nps_fields_to_cliente
Create Date: 2026-01-07 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_observacoes_cliente'
down_revision = 'add_nps_fields_to_cliente'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('observacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'observacoes')
    # ### end Alembic commands ###
