"""add_usuario_crm_id_to_chatbot_regra

Revision ID: f8a549bc73a8
Revises: 3e2d88648226
Create Date: 2026-01-11 19:27:06.406903

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f8a549bc73a8'
down_revision = '3e2d88648226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_regra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_crm_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario_crm', ['usuario_crm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_regra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_crm_id')
    # ### end Alembic commands ###
